#!/usr/bin/env python
# -*- encoding: utf-8 -*-

import rospy, sys
import numpy as np
from urdf_parser_py.urdf import URDF
import tf2_ros, tf2_geometry_msgs
from geometry_msgs.msg import Point

from center_points.utils import PointCommunicator, Point_to_numpy, numpy_to_Point, urdf_link_map # type: ignore

def calc_cop():
    buffer = tf2_ros.Buffer()
    tf2_ros.TransformListener(buffer)

    cop = np.array([0,0,0])
    return cop

def main():
    rospy.init_node('center_of_pressure', anonymous=False)
    cop_communicator = PointCommunicator('center_of_pressure')
    while not rospy.is_shutdown():
        cop = calc_cop()
        try:
            cop_communicator.publish_point(cop)
        except rospy.ROSInterruptException:
            pass

if __name__ == '__main__':
    main()
