#!/usr/bin/env python
# -*- encoding: utf-8 -*-

import rospy, sys
import numpy as np
from urdf_parser_py.urdf import URDF
import tf2_ros
from sensor_msgs.msg import Imu, JointState

from center_points.utils import PointCommunicator, Point_to_numpy, numpy_to_Point, urdf_link_map # type: ignore

imu = Imu()

def calc_zmp(imu : Imu):

    zmp = np.array([0,0,0])
    return zmp

def publish_zmp(imu : Imu, com : PointCommunicator):
    com.publish_point(calc_zmp(imu))
    rospy.loginfo(imu)

def main():
    rospy.init_node('zero_moment_point', anonymous=False)
    zmp_communicator = PointCommunicator('zero_moment_point')
    sub = rospy.Subscriber('base_imu', Imu, publish_zmp, zmp_communicator)
    rospy.spin()

if __name__ == '__main__':
    main()
